### ISSUE TITLE
Suggestion: sync order of expected/actual with failure messages

### ISSUE THREAD

**Issue by rtfeldman** [TheSeamau5/elm-check#14]
`Check.Test.test` currently takes `actual` and then `expected`, in that order.

However, if you get a failure, the output will of course list "Expected: " followed by "got:"

It would be nice if Expected consistently came first, both in argument order and in error message. The alternative is having to remember on a case-by-case basis which comes first for which part of the API.

**Comment by TheSeamau5** [comment]
I'm a bit conflicted on this one. Thing is I've made `Check.Test` to mirror the regular `Check` module which does `actual` then `expected` whereas elm-test does it the other way round. The reason I chose this order is cuz with the DSL it reads nicer

```elm
claim
  "Some claim"
  `that`
    actualStatement
  `is`
    expectedStatement
  `for`
    someInvestigator
```

**Comment by rtfeldman** [comment]
That reasoning makes sense. :smiley: 

It's honestly not a huge deal to me one way or the other, as personally I'm using partial application to pre-populate the run count and seed, and I just flip the arguments while I'm at it...just thought I'd bring it up in case the ordering had been chosen arbitrarily and there was only an upside to changing it.
