### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by Dandandan** [TheSeamau5/elm-check#18]
Right now when using elm-check, elm-shrink still does give a building error because a new version of elm-check hasn't been published.
When do you plan to release a new version with the upgrade?

Thanks,

Daniël

**Comment by TheSeamau5** [comment]
Oops, I forgot to sync to github after running elm package bump. It should be fixed now, hopefully.

**Comment by Dandandan** [comment]
I actually think it was OK, I believe I forgot to include the module elm-shrink itself.
Sorry for the confusion!
