### ISSUE TITLE
Update for Elm 0.15

### ISSUE THREAD

**Issue by wyleyr** [TheSeamau5/elm-check#7]
I've just (re-)installed Elm, and I'd like to use a library that depends on this one in a new project. Elm 0.15, the version I installed, was apparently released very recently and introduces some changes that prevent this library from being installed via elm-package. There are at least three things I've run into that need to be fixed:

1. Add an "elm-version" declaration in elm-package.json
2. Use the new import syntax: "import Mod (..)" should become "import Mod exposing (..)"
3. Deal with Maybe values returned by List.head

I'll send a pull request with my quick fixes for these issues shortly

**Comment by TheSeamau5** [comment]
Thanks for your help but I'm close to releasing the new version of elm-check (within a day or two). You can read an explanation of why I can't accept the simple merge here: https://github.com/TheSeamau5/elm-check/pull/8

Sorry for the trouble.
